name: ahsd
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - aiobotocore=2.24.2
  - aiohappyeyeballs=2.6.1
  - aiohttp=3.12.15
  - aioitertools=0.12.0
  - aiosignal=1.4.0
  - alsa-lib=1.2.14
  - aom=3.6.1
  - arviz=0.22.0
  - astropy=7.1.0
  - astropy-base=7.1.0
  - astropy-iers-data=0.2025.9.15.0.37.0
  - asttokens=3.0.0
  - attr=2.5.2
  - attrs=25.3.0
  - aws-c-auth=0.7.22
  - aws-c-cal=0.6.14
  - aws-c-common=0.9.19
  - aws-c-compression=0.2.18
  - aws-c-event-stream=0.4.2
  - aws-c-http=0.8.1
  - aws-c-io=0.14.8
  - aws-c-mqtt=0.10.4
  - aws-c-s3=0.5.9
  - aws-c-sdkutils=0.1.16
  - aws-checksums=0.1.18
  - aws-crt-cpp=0.26.9
  - aws-sdk-cpp=1.11.329
  - azure-core-cpp=1.13.0
  - azure-identity-cpp=1.9.0
  - azure-storage-blobs-cpp=12.13.0
  - azure-storage-common-cpp=12.8.0
  - azure-storage-files-datalake-cpp=12.12.0
  - bcrypt=4.3.0
  - beautifulsoup4=4.13.5
  - bilby=2.6.0
  - bilby.cython=0.5.3
  - blas=1.0
  - bleach=6.2.0
  - botocore=1.40.18
  - bottleneck=1.6.0
  - bqplot=0.12.45
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - brotli-python=1.1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.9.9
  - cached-property=1.5.2
  - cached_property=1.5.2
  - cairo=1.18.0
  - certifi=2025.8.3
  - cffi=1.17.1
  - cfitsio=4.6.2
  - charset-normalizer=3.4.3
  - click=8.2.1
  - cloudpickle=3.1.1
  - colorama=0.4.6
  - comm=0.2.3
  - contourpy=1.3.3
  - corner=2.2.3
  - cpuonly=2.0
  - cpython=3.11.13
  - cryptography=45.0.7
  - cycler=0.12.1
  - cyrus-sasl=2.1.28
  - cython=3.1.4
  - dask-core=2025.9.0
  - dateparser=1.2.2
  - dbus=1.13.6
  - debugpy=1.8.16
  - decorator=5.2.1
  - dill=0.4.0
  - double-conversion=3.3.1
  - dqsegdb2=1.3.0
  - dynesty=2.1.5
  - emcee=3.1.6
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - ffmpeg=4.4.2
  - fftw=3.3.10
  - filelock=3.19.1
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - fonttools=4.59.2
  - freetype=2.12.1
  - frozenlist=1.7.0
  - fsspec=2025.9.0
  - future=1.0.0
  - gast=0.4.0
  - gettext=0.25.1
  - gettext-tools=0.25.1
  - gflags=2.2.2
  - giflib=5.2.2
  - glib=2.84.0
  - glib-tools=2.84.0
  - glog=0.7.1
  - gmp=6.3.0
  - gmpy2=2.2.1
  - gnutls=3.7.9
  - graphite2=1.3.14
  - gsl=2.7
  - gst-plugins-base=1.24.7
  - gstreamer=1.24.7
  - gwdatafind=2.1.0
  - gwosc=0.8.1
  - gwpy=3.0.13
  - h2=4.3.0
  - h5netcdf=1.6.4
  - h5py=3.13.0
  - harfbuzz=9.0.0
  - hdf5=1.14.3
  - healpy=1.18.1
  - hpack=4.1.0
  - htgettoken=2.4
  - html5lib=1.1
  - hyperframe=6.1.0
  - icu=75.1
  - idna=3.10
  - igwn-auth-utils=1.4.0
  - igwn-ligolw=2.1.0
  - igwn-segments=2.1.0
  - importlib-metadata=8.7.0
  - iniconfig=2.0.0
  - invoke=2.2.0
  - ipydatagrid=1.4.0
  - ipykernel=6.30.1
  - ipython=9.5.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - jedi=0.19.2
  - jinja2=3.1.6
  - jmespath=1.0.1
  - joblib=1.5.2
  - jplephem=2.23
  - jq=1.8.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_widgets=3.0.15
  - keyutils=1.6.3
  - kiwisolver=1.4.9
  - krb5=1.21.3
  - lal=7.7.0
  - lalapps=10.1.0
  - lalburst=2.0.7
  - lalframe=3.0.7
  - lalinference=4.1.9
  - lalinference-data=4.1.9
  - lalinspiral=5.0.3
  - lalmetaio=4.0.6
  - lalpulsar=7.1.1
  - lalpulsar-data=7.1.1
  - lalsimulation=6.2.0
  - lalsimulation-data=6.2.0
  - lalsuite=7.26
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - ldas-tools-al=2.6.7
  - ldas-tools-framecpp=2.9.3
  - lerc=4.0.0
  - libabseil=20240116.2
  - libaec=1.1.4
  - libarrow=16.1.0
  - libarrow-acero=16.1.0
  - libarrow-dataset=16.1.0
  - libarrow-substrait=16.1.0
  - libasprintf=0.25.1
  - libasprintf-devel=0.25.1
  - libblas=3.9.0
  - libboost=1.86.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcap=2.71
  - libcblas=3.9.0
  - libclang-cpp15=15.0.7
  - libclang-cpp18.1=18.1.7
  - libclang-cpp19.1=19.1.7
  - libclang13=19.1.7
  - libcrc32c=1.1.2
  - libcups=2.3.3
  - libcurl=8.14.1
  - libdeflate=1.22
  - libdrm=2.4.125
  - libedit=3.1.20250104
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libexpat=2.7.1
  - libffi=3.4.4
  - libflac=1.4.3
  - libframel=8.47.2
  - libgcc=15.1.0
  - libgcc-ng=15.1.0
  - libgcrypt-lib=1.11.1
  - libgettextpo=0.25.1
  - libgettextpo-devel=0.25.1
  - libgfortran=15.1.0
  - libgfortran-ng=15.1.0
  - libgfortran5=15.1.0
  - libgl=1.7.0
  - libglib=2.84.0
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=15.1.0
  - libgoogle-cloud=2.24.0
  - libgoogle-cloud-storage=2.24.0
  - libgpg-error=1.55
  - libgrpc=1.62.2
  - libhwloc=2.11.2
  - libiconv=1.18
  - libidn2=2.3.8
  - libjpeg-turbo=3.1.0
  - liblal=7.7.0
  - liblalburst=2.0.7
  - liblalframe=3.0.7
  - liblalinference=4.1.9
  - liblalinspiral=5.0.3
  - liblalmetaio=4.0.6
  - liblalpulsar=7.1.1
  - liblalsimulation=6.2.0
  - liblapack=3.9.0
  - libllvm15=15.0.7
  - libllvm18=18.1.7
  - libllvm19=19.1.7
  - libmetaio=8.5.1
  - libnghttp2=1.67.0
  - libnsl=2.0.1
  - libntlm=1.8
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopengl=1.7.0
  - libopentelemetry-cpp=1.15.0
  - libopentelemetry-cpp-headers=1.15.0
  - libopus=1.5.2
  - libparquet=16.1.0
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=16.10
  - libprotobuf=4.25.3
  - libre2-11=2023.09.01
  - libsndfile=1.2.2
  - libsodium=1.0.20
  - libsqlite=3.50.4
  - libssh2=1.11.1
  - libstdcxx=15.1.0
  - libstdcxx-ng=15.1.0
  - libsystemd0=256.9
  - libtasn1=4.20.0
  - libthrift=0.19.0
  - libtiff=4.7.0
  - libunistring=0.9.10
  - libutf8proc=2.8.0
  - libuuid=2.41.1
  - libva=2.22.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.4.0
  - libwebp-base=1.4.0
  - libxcb=1.17.0
  - libxcrypt=4.4.36
  - libxkbcommon=1.8.0
  - libxml2=2.13.5
  - libxslt=1.1.39
  - libzlib=1.3.1
  - ligo-gracedb=2.14.2
  - ligo-segments=1.4.0
  - ligotimegps=2.0.1
  - llvm-openmp=15.0.7
  - locket=1.0.0
  - lscsoft-glue=4.1.0
  - lz4-c=1.9.4
  - mako=1.3.10
  - markupsafe=3.0.2
  - matplotlib=3.9.1
  - matplotlib-base=3.9.1
  - matplotlib-inline=0.1.7
  - mkl=2023.2.0
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpg123=1.32.9
  - mpld3=0.5.11
  - mpmath=1.3.0
  - multidict=6.6.3
  - munkres=1.1.4
  - mysql-common=9.0.1
  - mysql-libs=9.0.1
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - nettle=3.9.1
  - networkx=3.5
  - nlohmann_json=3.12.0
  - nspr=4.37
  - nss=3.116
  - numpy=2.3.3
  - oniguruma=6.9.10
  - openh264=2.3.1
  - openjpeg=2.5.2
  - openldap=2.6.10
  - openssl=3.5.3
  - orc=2.0.1
  - p11-kit=0.24.1
  - packaging=25.0
  - pandas=2.3.2
  - paramiko=4.0.0
  - parso=0.8.5
  - partd=1.4.2
  - pcre2=10.44
  - pegasus-wms.api=5.0.9
  - pegasus-wms.common=5.0.9
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.0.0
  - pip=25.2
  - pixman=0.46.4
  - pkg-config=0.29.2
  - platformdirs=4.4.0
  - pluggy=1.6.0
  - ply=3.11
  - prometheus-cpp=1.2.4
  - prompt-toolkit=3.0.52
  - propcache=0.3.1
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pulseaudio-client=17.0
  - pure_eval=0.2.3
  - py2vega=0.6.1
  - pyarrow=16.1.0
  - pyarrow-core=16.1.0
  - pycbc=2.8.2
  - pycparser=2.22
  - pyerfa=2.0.1.5
  - pygments=2.19.2
  - pyjwt=2.10.1
  - pykerr=0.1.0
  - pynacl=1.6.0
  - pyparsing=3.2.4
  - pyqt=5.15.9
  - pyqt5-sip=12.12.2
  - pyside6=6.7.3
  - pysocks=1.7.1
  - pytest=8.4.2
  - python=3.11.9
  - python-dateutil=2.9.0.post0
  - python-gssapi=1.10.0
  - python-lal=7.7.0
  - python-lalburst=2.0.7
  - python-lalframe=3.0.7
  - python-lalinference=4.1.9
  - python-lalinspiral=5.0.3
  - python-lalmetaio=4.0.6
  - python-lalpulsar=7.1.1
  - python-lalsimulation=6.2.0
  - python-ligo-lw=1.8.3
  - python-tzdata=2025.2
  - python_abi=3.11
  - pytorch=2.5.1
  - pytorch-mutex=1.0
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.1.0
  - qhull=2020.2
  - qt-main=5.15.8
  - qt6-main=6.7.3
  - re2=2023.09.01
  - readline=8.3
  - regex=2025.9.1
  - requests=2.32.5
  - s2n=1.4.15
  - s3fs=2025.9.0
  - safe-netrc=1.0.1
  - scikit-learn=1.7.2
  - scipy=1.16.2
  - scitokens=1.8.1
  - setuptools=78.1.1
  - sip=6.7.12
  - six=1.17.0
  - snappy=1.2.2
  - sortedcontainers=2.4.0
  - soupsieve=2.8
  - sqlite=3.50.2
  - stack_data=0.6.3
  - svt-av1=1.4.1
  - tbb=2021.13.0
  - threadpoolctl=3.6.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - toolz=1.0.0
  - torchaudio=2.5.1
  - torchvision=0.20.1
  - tornado=6.5.2
  - tqdm=4.67.1
  - traitlets=5.14.3
  - traittypes=0.2.1
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - tzlocal=5.3.1
  - uncompresspy=0.4.0
  - unicodedata2=16.0.0
  - urllib3=2.5.0
  - wayland=1.23.1
  - wayland-protocols=1.45
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - wheel=0.45.1
  - widgetsnbextension=4.0.14
  - wrapt=1.17.3
  - x264=1!164.3095
  - x265=3.5
  - xarray=2025.9.0
  - xarray-einstats=0.9.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.42
  - xorg-compositeproto=0.4.2
  - xorg-damageproto=1.2.1
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxcomposite=0.4.6
  - xorg-libxcursor=1.2.0
  - xorg-libxdamage=1.1.5
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrandr=1.5.2
  - xorg-libxrender=0.9.11
  - xorg-libxtst=1.2.5
  - xorg-libxxf86vm=1.1.5
  - xorg-randrproto=1.5.0
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-util-macros=1.20.2
  - xorg-xextproto=7.3.0
  - xorg-xf86vidmodeproto=2.3.1
  - xorg-xorgproto=2024.1
  - xorg-xproto=7.0.31
  - xz=5.6.4
  - yaml=0.2.5
  - yarl=1.20.1
  - zeromq=4.3.5
  - zipp=3.23.0
  - zlib=1.3.1
  - zstandard=0.23.0
  - zstd=1.5.7
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - blosc2==3.11.1
      - e==1.4.5
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.75.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - markdown==3.9
      - msgpack==1.1.2
      - ndindex==1.10.1
      - nflows==0.14
      - numexpr==2.14.1
      - nvidia-nccl-cu12==2.28.3
      - omegaconf==2.3.0
      - posteriflow==1.0.0
      - protobuf==6.32.1
      - py-cpuinfo==9.0.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - safetensors==0.7.0
      - seaborn==0.13.2
      - sentry-sdk==2.38.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tables==3.10.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.22.1
      - transformers==4.57.1
      - typing-inspection==0.4.1
      - wandb==0.21.4
      - werkzeug==3.1.3
      - xgboost==3.0.5
prefix: /home/bibin/miniconda3/envs/ahsd
