name: ahsd
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=4_kmp_llvm
  - aiobotocore=2.24.2=pyhcf101f3_0
  - aiohappyeyeballs=2.6.1=pyhd8ed1ab_0
  - aiohttp=3.12.15=py311h3778330_0
  - aioitertools=0.12.0=pyhd8ed1ab_1
  - aiosignal=1.4.0=pyhd8ed1ab_0
  - alsa-lib=1.2.14=hb9d3cd8_0
  - aom=3.6.1=h59595ed_0
  - arviz=0.22.0=pyhd8ed1ab_0
  - astropy=7.1.0=pyhd8ed1ab_1
  - astropy-base=7.1.0=py311h52c8da0_1
  - astropy-iers-data=0.2025.9.15.0.37.0=pyhd8ed1ab_0
  - asttokens=3.0.0=pyhd8ed1ab_1
  - attr=2.5.2=h39aace5_0
  - attrs=25.3.0=pyh71513ae_0
  - aws-c-auth=0.7.22=h96bc93b_2
  - aws-c-cal=0.6.14=h88a6e22_1
  - aws-c-common=0.9.19=h4ab18f5_0
  - aws-c-compression=0.2.18=h83b837d_6
  - aws-c-event-stream=0.4.2=ha47c788_12
  - aws-c-http=0.8.1=h29d6fba_17
  - aws-c-io=0.14.8=h21d4f22_5
  - aws-c-mqtt=0.10.4=h759edc4_4
  - aws-c-s3=0.5.9=h594631b_3
  - aws-c-sdkutils=0.1.16=h83b837d_2
  - aws-checksums=0.1.18=h83b837d_6
  - aws-crt-cpp=0.26.9=he3a8b3b_0
  - aws-sdk-cpp=1.11.329=hba8bd5f_3
  - azure-core-cpp=1.13.0=h935415a_0
  - azure-identity-cpp=1.9.0=hd126650_0
  - azure-storage-blobs-cpp=12.13.0=h1d30c4a_0
  - azure-storage-common-cpp=12.8.0=ha3822c6_0
  - azure-storage-files-datalake-cpp=12.12.0=h0f25b8a_0
  - bcrypt=4.3.0=py311h902ca64_2
  - beautifulsoup4=4.13.5=pyha770c72_0
  - bilby=2.6.0=pyhd8ed1ab_1
  - bilby.cython=0.5.3=py311h0372a8f_0
  - blas=1.0=mkl
  - bleach=6.2.0=pyh29332c3_4
  - botocore=1.40.18=pyhd8ed1ab_0
  - bottleneck=1.6.0=py311h0372a8f_0
  - bqplot=0.12.45=pyhe01879c_0
  - brotli=1.1.0=hb03c661_4
  - brotli-bin=1.1.0=hb03c661_4
  - brotli-python=1.1.0=py311h1ddb823_4
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hb9d3cd8_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - cairo=1.18.0=hebfffa5_3
  - certifi=2025.8.3=pyhd8ed1ab_0
  - cffi=1.17.1=py311hf29c0ef_0
  - cfitsio=4.6.2=ha0b56bc_1
  - charset-normalizer=3.4.3=pyhd8ed1ab_0
  - click=8.2.1=pyh707e725_0
  - cloudpickle=3.1.1=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.3=pyhe01879c_0
  - contourpy=1.3.3=py311hdf67eae_2
  - corner=2.2.3=pyhd8ed1ab_1
  - cpuonly=2.0=0
  - cpython=3.11.13=py311hd8ed1ab_0
  - cryptography=45.0.7=py311h8488d03_1
  - cycler=0.12.1=pyhd8ed1ab_1
  - cyrus-sasl=2.1.28=hd9c7081_0
  - cython=3.1.4=py311h91b4c63_2
  - dask-core=2025.9.0=pyhcf101f3_0
  - dateparser=1.2.2=pyhd8ed1ab_0
  - dbus=1.13.6=h5008d03_3
  - debugpy=1.8.16=py311hc665b79_1
  - decorator=5.2.1=pyhd8ed1ab_0
  - dill=0.4.0=pyhd8ed1ab_0
  - double-conversion=3.3.1=h5888daf_0
  - dqsegdb2=1.3.0=pyhd8ed1ab_0
  - dynesty=2.1.5=pyhd8ed1ab_0
  - emcee=3.1.6=pyhd8ed1ab_1
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=pyhd8ed1ab_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=4.4.2=gpl_hdf48244_113
  - fftw=3.3.10=nompi_hf1063bd_110
  - filelock=3.19.1=pyhd8ed1ab_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.14.2=h14ed4e7_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.59.2=py311h3778330_0
  - freetype=2.12.1=h267a509_2
  - frozenlist=1.7.0=py311h52bc045_0
  - fsspec=2025.9.0=pyhd8ed1ab_0
  - future=1.0.0=pyhd8ed1ab_2
  - gast=0.4.0=pyh9f0ad1d_0
  - gettext=0.25.1=h3f43e3d_1
  - gettext-tools=0.25.1=h3f43e3d_1
  - gflags=2.2.2=h5888daf_1005
  - giflib=5.2.2=hd590300_0
  - glib=2.84.0=h07242d1_0
  - glib-tools=2.84.0=h4833e2c_0
  - glog=0.7.1=hbabe93e_0
  - gmp=6.3.0=hac33072_2
  - gmpy2=2.2.1=py311h92a432a_1
  - gnutls=3.7.9=hb077bed_0
  - graphite2=1.3.14=hecca717_2
  - gsl=2.7=he838d99_0
  - gst-plugins-base=1.24.7=h0a52356_0
  - gstreamer=1.24.7=hf3bb09a_0
  - gwdatafind=2.1.0=pyh707e725_0
  - gwosc=0.8.1=pyhd8ed1ab_0
  - gwpy=3.0.13=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - h5netcdf=1.6.4=pyhd8ed1ab_0
  - h5py=3.13.0=nompi_py311hb639ac4_100
  - harfbuzz=9.0.0=hda332d3_1
  - hdf5=1.14.3=nompi_hdf9ad27_105
  - healpy=1.18.1=py311h1cbb2fd_2
  - hpack=4.1.0=pyhd8ed1ab_0
  - htgettoken=2.4=py311h38be061_1
  - html5lib=1.1=pyhd8ed1ab_2
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=he02047a_0
  - idna=3.10=pyhd8ed1ab_1
  - igwn-auth-utils=1.4.0=pyh707e725_0
  - igwn-ligolw=2.1.0=py311h9ecbd09_0
  - igwn-segments=2.1.0=py311h9ecbd09_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - iniconfig=2.0.0=pyhd8ed1ab_1
  - invoke=2.2.0=pyhd8ed1ab_1
  - ipydatagrid=1.4.0=pyhcf101f3_2
  - ipykernel=6.30.1=pyh82676e8_0
  - ipython=9.5.0=pyhfa0c392_0
  - ipython_pygments_lexers=1.1.1=pyhd8ed1ab_0
  - ipywidgets=8.1.7=pyhd8ed1ab_0
  - jedi=0.19.2=pyhd8ed1ab_1
  - jinja2=3.1.6=pyhd8ed1ab_0
  - jmespath=1.0.1=pyhd8ed1ab_1
  - joblib=1.5.2=pyhd8ed1ab_0
  - jplephem=2.23=pyha4b2019_0
  - jq=1.8.1=h73b1eb8_0
  - jupyter_client=8.6.3=pyhd8ed1ab_1
  - jupyter_core=5.8.1=pyh31011fe_0
  - jupyterlab_widgets=3.0.15=pyhd8ed1ab_0
  - keyutils=1.6.3=hb9d3cd8_0
  - kiwisolver=1.4.9=py311h724c32c_1
  - krb5=1.21.3=h659f571_0
  - lal=7.7.0=fftw_py311h5bca7b8_100
  - lalapps=10.1.0=py311ha13a6dd_0
  - lalburst=2.0.7=py311h9ecbd09_0
  - lalframe=3.0.7=py311h9ecbd09_0
  - lalinference=4.1.9=nompi_py311ha5d293d_100
  - lalinference-data=4.1.9=ha770c72_0
  - lalinspiral=5.0.3=py311h9ecbd09_0
  - lalmetaio=4.0.6=py311h9ecbd09_0
  - lalpulsar=7.1.1=py311hb946fa8_0
  - lalpulsar-data=7.1.1=ha770c72_0
  - lalsimulation=6.2.0=py311h33ea901_0
  - lalsimulation-data=6.2.0=ha770c72_0
  - lalsuite=7.26=pyhd8ed1ab_0
  - lame=3.100=h166bdaf_1003
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - ldas-tools-al=2.6.7=h2b4839b_6
  - ldas-tools-framecpp=2.9.3=hcc7daa0_3
  - lerc=4.0.0=h0aef613_1
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.4=h3f801dc_0
  - libarrow=16.1.0=hcb6531f_6_cpu
  - libarrow-acero=16.1.0=hac33072_6_cpu
  - libarrow-dataset=16.1.0=hac33072_6_cpu
  - libarrow-substrait=16.1.0=h7e0c224_6_cpu
  - libasprintf=0.25.1=h3f43e3d_1
  - libasprintf-devel=0.25.1=h3f43e3d_1
  - libblas=3.9.0=20_linux64_mkl
  - libboost=1.86.0=hb8260a3_2
  - libbrotlicommon=1.1.0=hb03c661_4
  - libbrotlidec=1.1.0=hb03c661_4
  - libbrotlienc=1.1.0=hb03c661_4
  - libcap=2.71=h39aace5_0
  - libcblas=3.9.0=20_linux64_mkl
  - libclang-cpp15=15.0.7=default_h127d8a8_5
  - libclang-cpp18.1=18.1.7=default_h9bb3924_0
  - libclang-cpp19.1=19.1.7=default_h99862b1_4
  - libclang13=19.1.7=default_h746c552_4
  - libcrc32c=1.1.2=h9c3ff4c_0
  - libcups=2.3.3=h4637d8d_4
  - libcurl=8.14.1=h332b0f4_0
  - libdeflate=1.22=hb9d3cd8_0
  - libdrm=2.4.125=hb03c661_1
  - libedit=3.1.20250104=pl5321h7949ede_0
  - libegl=1.7.0=ha4b6fd6_0
  - libev=4.33=hd590300_2
  - libevent=2.1.12=hf998b51_1
  - libexpat=2.7.1=hecca717_0
  - libffi=3.4.4=h6a678d5_1
  - libflac=1.4.3=h59595ed_0
  - libframel=8.47.2=hb9d3cd8_2
  - libgcc=15.1.0=h767d61c_5
  - libgcc-ng=15.1.0=h69a702a_5
  - libgcrypt-lib=1.11.1=hb9d3cd8_0
  - libgettextpo=0.25.1=h3f43e3d_1
  - libgettextpo-devel=0.25.1=h3f43e3d_1
  - libgfortran=15.1.0=h69a702a_5
  - libgfortran-ng=15.1.0=h69a702a_5
  - libgfortran5=15.1.0=hcea5267_5
  - libgl=1.7.0=ha4b6fd6_0
  - libglib=2.84.0=h2ff4ddf_0
  - libglvnd=1.7.0=ha4b6fd6_0
  - libglx=1.7.0=ha4b6fd6_0
  - libgomp=15.1.0=h767d61c_5
  - libgoogle-cloud=2.24.0=h2736e30_0
  - libgoogle-cloud-storage=2.24.0=h3d9a0c8_0
  - libgpg-error=1.55=h3f2d84a_0
  - libgrpc=1.62.2=h15f2491_0
  - libhwloc=2.11.2=default_he43201b_1000
  - libiconv=1.18=h3b78370_2
  - libidn2=2.3.8=ha4ef2c3_0
  - libjpeg-turbo=3.1.0=hb9d3cd8_0
  - liblal=7.7.0=fftw_hcbe9c14_100
  - liblalburst=2.0.7=h3773ae6_0
  - liblalframe=3.0.7=h7c287a6_0
  - liblalinference=4.1.9=h3773ae6_0
  - liblalinspiral=5.0.3=h3773ae6_0
  - liblalmetaio=4.0.6=hb9d3cd8_0
  - liblalpulsar=7.1.1=h9345056_0
  - liblalsimulation=6.2.0=py311h33ea901_0
  - liblapack=3.9.0=20_linux64_mkl
  - libllvm15=15.0.7=hb3ce162_4
  - libllvm18=18.1.7=hb77312f_0
  - libllvm19=19.1.7=ha7bfdaf_1
  - libmetaio=8.5.1=h0b0be96_1003
  - libnghttp2=1.67.0=had1ee68_0
  - libnsl=2.0.1=hb9d3cd8_1
  - libntlm=1.8=hb9d3cd8_0
  - libogg=1.3.5=hd0c01bc_1
  - libopenblas=0.3.30=pthreads_h94d23a6_2
  - libopengl=1.7.0=ha4b6fd6_0
  - libopentelemetry-cpp=1.15.0=h66972aa_0
  - libopentelemetry-cpp-headers=1.15.0=ha770c72_0
  - libopus=1.5.2=hd0c01bc_0
  - libparquet=16.1.0=h6a7eafb_6_cpu
  - libpciaccess=0.18=hb9d3cd8_0
  - libpng=1.6.50=h421ea60_1
  - libpq=16.10=h1cdf469_2
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsndfile=1.2.2=hc60ed4a_1
  - libsodium=1.0.20=h4ab18f5_0
  - libsqlite=3.50.4=h0c1763c_0
  - libssh2=1.11.1=hcf80075_0
  - libstdcxx=15.1.0=h8f9b012_5
  - libstdcxx-ng=15.1.0=h4852527_5
  - libsystemd0=256.9=h2774228_0
  - libtasn1=4.20.0=hb9d3cd8_0
  - libthrift=0.19.0=hb90f79a_1
  - libtiff=4.7.0=he137b08_1
  - libunistring=0.9.10=h7f98852_0
  - libutf8proc=2.8.0=hf23e847_1
  - libuuid=2.41.1=he9a06e4_0
  - libva=2.22.0=h8a09558_1
  - libvorbis=1.3.7=h54a6638_2
  - libvpx=1.13.1=h59595ed_0
  - libwebp=1.4.0=h2c329e2_0
  - libwebp-base=1.4.0=hd590300_0
  - libxcb=1.17.0=h8a09558_0
  - libxcrypt=4.4.36=hd590300_1
  - libxkbcommon=1.8.0=hc4a0caf_0
  - libxml2=2.13.5=hb346dea_0
  - libxslt=1.1.39=h76b75d6_0
  - libzlib=1.3.1=hb9d3cd8_2
  - ligo-gracedb=2.14.2=pyhd8ed1ab_0
  - ligo-segments=1.4.0=py311h9ecbd09_6
  - ligotimegps=2.0.1=pyhd8ed1ab_1
  - llvm-openmp=15.0.7=h0cdce71_0
  - locket=1.0.0=pyhd8ed1ab_0
  - lscsoft-glue=4.1.0=pyhd8ed1ab_0
  - lz4-c=1.9.4=hcb278e6_0
  - mako=1.3.10=pyhd8ed1ab_0
  - markupsafe=3.0.2=py311h2dc5d0c_1
  - matplotlib=3.9.1=py311h38be061_1
  - matplotlib-base=3.9.1=py311h74b4f7c_2
  - matplotlib-inline=0.1.7=pyhd8ed1ab_1
  - mkl=2023.2.0=ha770c72_50498
  - mpc=1.3.1=h24ddda3_1
  - mpfr=4.2.1=h90cbb55_3
  - mpg123=1.32.9=hc50e24c_0
  - mpld3=0.5.11=pyhd8ed1ab_0
  - mpmath=1.3.0=pyhd8ed1ab_1
  - multidict=6.6.3=py311h2dc5d0c_0
  - munkres=1.1.4=pyhd8ed1ab_1
  - mysql-common=9.0.1=h266115a_6
  - mysql-libs=9.0.1=he0572af_6
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_1
  - nettle=3.9.1=h7ab15ed_0
  - networkx=3.5=pyhe01879c_0
  - nlohmann_json=3.12.0=h3f2d84a_0
  - nspr=4.37=h29cc59b_0
  - nss=3.116=h445c969_0
  - numpy=2.3.3=py311h2e04523_0
  - oniguruma=6.9.10=hb9d3cd8_0
  - openh264=2.3.1=hcb278e6_2
  - openjpeg=2.5.2=h488ebb8_0
  - openldap=2.6.10=he970967_0
  - openssl=3.5.3=h26f9b46_0
  - orc=2.0.1=h17fec99_1
  - p11-kit=0.24.1=hc5aa10d_0
  - packaging=25.0=pyh29332c3_1
  - pandas=2.3.2=py311hed34c8f_0
  - paramiko=4.0.0=pyhd8ed1ab_0
  - parso=0.8.5=pyhcf101f3_0
  - partd=1.4.2=pyhd8ed1ab_0
  - pcre2=10.44=hc749103_2
  - pegasus-wms.api=5.0.9=pyhd8ed1ab_0
  - pegasus-wms.common=5.0.9=pyhd8ed1ab_0
  - pexpect=4.9.0=pyhd8ed1ab_1
  - pickleshare=0.7.5=pyhd8ed1ab_1004
  - pillow=11.0.0=py311h49e9ac3_0
  - pip=25.2=pyhc872135_0
  - pixman=0.46.4=h54a6638_1
  - pkg-config=0.29.2=h4bc722e_1009
  - platformdirs=4.4.0=pyhcf101f3_0
  - pluggy=1.6.0=pyhd8ed1ab_0
  - ply=3.11=pyhd8ed1ab_3
  - prometheus-cpp=1.2.4=h90a924e_0
  - prompt-toolkit=3.0.52=pyha770c72_0
  - propcache=0.3.1=py311h2dc5d0c_0
  - psutil=7.0.0=py311h49ec1c0_1
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd8ed1ab_1
  - pulseaudio-client=17.0=hb77b528_0
  - pure_eval=0.2.3=pyhd8ed1ab_1
  - py2vega=0.6.1=pyhd8ed1ab_0
  - pyarrow=16.1.0=py311hbd00459_2
  - pyarrow-core=16.1.0=py311hf1d6e26_2_cpu
  - pycbc=2.8.2=py311h862733e_0
  - pycparser=2.22=pyh29332c3_1
  - pyerfa=2.0.1.5=py310h32771cd_2
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyjwt=2.10.1=pyhd8ed1ab_0
  - pykerr=0.1.0=pyhd8ed1ab_0
  - pynacl=1.6.0=py311h49ec1c0_0
  - pyparsing=3.2.4=pyhcf101f3_0
  - pyqt=5.15.9=py311hf0fb5b6_5
  - pyqt5-sip=12.12.2=py311hb755f60_5
  - pyside6=6.7.3=py311h9053184_1
  - pysocks=1.7.1=pyha55dd90_7
  - pytest=8.4.2=pyhd8ed1ab_0
  - python=3.11.9=hb806964_0_cpython
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-gssapi=1.10.0=py311he3cc2e5_0
  - python-lal=7.7.0=fftw_py311hb915d49_100
  - python-lalburst=2.0.7=py311h7f0001c_0
  - python-lalframe=3.0.7=py311h9f3472d_0
  - python-lalinference=4.1.9=py311h9f3472d_0
  - python-lalinspiral=5.0.3=py311h9f3472d_0
  - python-lalmetaio=4.0.6=py311h9f3472d_0
  - python-lalpulsar=7.1.1=py311h9f3472d_0
  - python-lalsimulation=6.2.0=py311h7f0001c_0
  - python-ligo-lw=1.8.3=py311h9ecbd09_4
  - python-tzdata=2025.2=pyhd8ed1ab_0
  - python_abi=3.11=8_cp311
  - pytorch=2.5.1=py3.11_cpu_0
  - pytorch-mutex=1.0=cpu
  - pytz=2025.2=pyhd8ed1ab_0
  - pyyaml=6.0.2=py311h2dc5d0c_2
  - pyzmq=27.1.0=py311h2315fbb_0
  - qhull=2020.2=h434a139_5
  - qt-main=5.15.8=h3155989_26
  - qt6-main=6.7.3=h20baabe_0
  - re2=2023.09.01=h7f4b329_2
  - readline=8.3=hc2a1206_0
  - regex=2025.9.1=py311h49ec1c0_0
  - requests=2.32.5=pyhd8ed1ab_0
  - s2n=1.4.15=he19d79f_0
  - s3fs=2025.9.0=pyhd8ed1ab_0
  - safe-netrc=1.0.1=pyhd8ed1ab_0
  - scikit-learn=1.7.2=py311hc3e1efb_0
  - scipy=1.16.2=py311h1e13796_0
  - scitokens=1.8.1=pyhd8ed1ab_0
  - setuptools=78.1.1=py311h06a4308_0
  - sip=6.7.12=py311hb755f60_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h03e3b7b_0
  - sortedcontainers=2.4.0=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.6.3=pyhd8ed1ab_1
  - svt-av1=1.4.1=hcb278e6_0
  - tbb=2021.13.0=hceb3a55_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.13=noxft_h4845f30_101
  - toml=0.10.2=pyhd8ed1ab_1
  - tomli=2.2.1=pyhe01879c_2
  - toolz=1.0.0=pyhd8ed1ab_1
  - torchaudio=2.5.1=py311_cpu
  - torchvision=0.20.1=py311_cpu
  - tornado=6.5.2=py311h49ec1c0_1
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=pyhd8ed1ab_1
  - traittypes=0.2.1=pyh9f0ad1d_2
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h04d1e81_0
  - tzlocal=5.3.1=pyh8f84b5b_0
  - uncompresspy=0.4.0=pyhd8ed1ab_0
  - unicodedata2=16.0.0=py311h49ec1c0_1
  - urllib3=2.5.0=pyhd8ed1ab_0
  - wayland=1.23.1=h3e06ad9_0
  - wayland-protocols=1.45=hd8ed1ab_0
  - wcwidth=0.2.13=pyhd8ed1ab_1
  - webencodings=0.5.1=pyhd8ed1ab_3
  - wheel=0.45.1=py311h06a4308_0
  - widgetsnbextension=4.0.14=pyhd8ed1ab_0
  - wrapt=1.17.3=py311h49ec1c0_1
  - x264=1!164.3095=h166bdaf_2
  - x265=3.5=h924138e_3
  - xarray=2025.9.0=pyhd8ed1ab_0
  - xarray-einstats=0.9.1=pyhd8ed1ab_0
  - xcb-util=0.4.1=h4f16b4b_2
  - xcb-util-cursor=0.1.5=hb9d3cd8_0
  - xcb-util-image=0.4.0=hb711507_2
  - xcb-util-keysyms=0.4.1=hb711507_0
  - xcb-util-renderutil=0.3.10=hb711507_0
  - xcb-util-wm=0.4.2=hb711507_0
  - xkeyboard-config=2.42=h4ab18f5_0
  - xorg-compositeproto=0.4.2=hb9d3cd8_1002
  - xorg-damageproto=1.2.1=hb9d3cd8_1003
  - xorg-fixesproto=5.0=hb9d3cd8_1003
  - xorg-inputproto=2.3.2=hb9d3cd8_1003
  - xorg-kbproto=1.0.7=hb9d3cd8_1003
  - xorg-libice=1.1.2=hb9d3cd8_0
  - xorg-libsm=1.2.6=he73a12e_0
  - xorg-libx11=1.8.12=h4f16b4b_0
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxcomposite=0.4.6=h0b41bf4_1
  - xorg-libxcursor=1.2.0=h0b41bf4_1
  - xorg-libxdamage=1.1.5=h7f98852_1
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.4=h0b41bf4_2
  - xorg-libxfixes=5.0.3=h7f98852_1004
  - xorg-libxi=1.7.10=h4bc722e_1
  - xorg-libxrandr=1.5.2=h7f98852_1
  - xorg-libxrender=0.9.11=hd590300_0
  - xorg-libxtst=1.2.5=h4bc722e_0
  - xorg-libxxf86vm=1.1.5=hb9d3cd8_2
  - xorg-randrproto=1.5.0=hb9d3cd8_1002
  - xorg-recordproto=1.14.2=hb9d3cd8_1003
  - xorg-renderproto=0.11.1=hb9d3cd8_1003
  - xorg-util-macros=1.20.2=hb9d3cd8_0
  - xorg-xextproto=7.3.0=hb9d3cd8_1004
  - xorg-xf86vidmodeproto=2.3.1=hb9d3cd8_1005
  - xorg-xorgproto=2024.1=hb9d3cd8_1
  - xorg-xproto=7.0.31=hb9d3cd8_1008
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h280c20c_3
  - yarl=1.20.1=py311h2dc5d0c_0
  - zeromq=4.3.5=h387f397_9
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib=1.3.1=hb9d3cd8_2
  - zstandard=0.23.0=py311h49ec1c0_3
  - zstd=1.5.7=hb8e6e7a_2
  - pip:
      - absl-py==2.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - blosc2==3.11.1
      - e==1.4.5
      - gitdb==4.0.12
      - gitpython==3.1.45
      - grpcio==1.75.0
      - hf-xet==1.2.0
      - huggingface-hub==0.36.0
      - hydra-core==1.3.2
      - markdown==3.9
      - msgpack==1.1.2
      - ndindex==1.10.1
      - nflows==0.14
      - numexpr==2.14.1
      - nvidia-nccl-cu12==2.28.3
      - omegaconf==2.3.0
      - posteriflow==1.0.0
      - protobuf==6.32.1
      - py-cpuinfo==9.0.0
      - pydantic==2.11.9
      - pydantic-core==2.33.2
      - readligo==0.6.1
      - safetensors==0.7.0
      - seaborn==0.13.2
      - sentry-sdk==2.38.0
      - smmap==5.0.2
      - sympy==1.13.1
      - tables==3.10.2
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - tokenizers==0.22.1
      - transformers==4.57.1
      - typing-inspection==0.4.1
      - wandb==0.21.4
      - werkzeug==3.1.3
      - xgboost==3.0.5
prefix: /home/bibin/miniconda3/envs/ahsd
